Feature.mgmtint
F5Networks/f5-common-python pull request #984
Opened 2017-02-15 23:04 UTC by jasonrahm

updated test cases to reflect jenkins environment

2017-02-16 00:22 UTC, jasonrahm commented
@wojtek0806 or @caphrim007 this is ready for review. Note that the create method doesn't fully test a working create and the delete method is not tested to protect the management interface connectivity for all other tests. That logic is there, just commented out.

2017-02-16 00:36 UTC, caphrim007 commented on f5/bigip/tm/sys/management_ip.py
> +# Copyright 2016 F5 Networks Inc.
we're now in 2017

2017-02-16 00:37 UTC, caphrim007 commented on f5/bigip/tm/sys/management_route.py
> +# Copyright 2016 F5 Networks Inc.
year

2017-02-16 00:38 UTC, caphrim007 commented on f5/bigip/tm/sys/test/functional/test_management_ip.py
> +# Copyright 2015-2106 F5 Networks Inc.
same year. also, needs the python shebang at the top

2017-02-16 00:39 UTC, caphrim007 commented
@jasonrahm can you really not update the management ip through the api?

2017-02-16 00:39 UTC, jasonrahm commented on f5/bigip/tm/sys/management_route.py
> +# Copyright 2016 F5 Networks Inc.
heh, I suppose I should read comment fields I copy over from other files more carefully...I can clean up here or I can submit a PR to update all source files for copyright info.

2017-02-16 00:40 UTC, caphrim007 commented on f5/bigip/tm/sys/management_route.py
> +# Copyright 2016 F5 Networks Inc.
we dont need to update all source files in the source tree for copyright, just the new files that we add.

2017-02-16 00:40 UTC, jasonrahm commented
You can update the management IP but it is done through create, not modify or update.

2017-02-16 00:42 UTC, caphrim007 commented
so you can create and you can delete, and updating is no different from creating?

2017-02-16 00:43 UTC, jasonrahm commented
A POST will overwrite existing management IP as long as it is different than the existing one. PUT/PATCH will not do anything to the management IP.

2017-02-16 00:44 UTC, caphrim007 commented
I'm wondering then if, for consistency and user experience's sake, if we should just alias modify commands to create

2017-02-16 00:51 UTC, jasonrahm commented on f5/bigip/tm/sys/test/functional/test_management_ip.py
> +# Copyright 2015-2106 F5 Networks Inc.
when did we start adding the shebang to files? I haven't seen that in the other modules

2017-02-16 00:51 UTC, jasonrahm commented
do you mean that we should only support .update() or .modify() , but in those, call the create method instead?

2017-02-16 01:28 UTC, caphrim007 commented
Ignore my shebang comment. You're correct.

For modify and update, yes, if it behaves where the experience of "updating" is essentially just calling create, then i would think the user would think they are updating, when in dact we're just calling create on their behalf

2017-02-16 01:39 UTC, jasonrahm commented
ok i will refactor, thanks

src: mobile

On Feb 15, 2017, at 7:28 PM, Tim Rupp <notifications@github.com<mailto:notifications@github.com>> wrote:


Ignore my shebang comment. You're correct.

For modify and update, yes, if it behaves where the experience of "updating" is essentially just calling create, then i would think the user would think they are updating, when in dact we're just calling create on their behalf

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/F5Networks/f5-common-python/pull/984#issuecomment-280200382>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AA0SSxDU2onMuow_8GNUNnywRn6km2PZks5rc6ZHgaJpZM4MCXct>.

2017-02-16 21:39 UTC, wojtek0806 commented
what happens if you don't have mgmt IP set?, i think it would be better if we leave create(), and just redo modify() or update() or both to use POST. This way this will be cleaner than aliasing and doing all weird voodoo stuff

@jasonrahm

2017-02-16 21:42 UTC, jasonrahm commented
yes, create needs to still be there for initial setting of management interface if absent.

From: Wojciech Wypior <notifications@github.com>
Reply-To: F5Networks/f5-common-python <reply@reply.github.com>
Date: Thursday, February 16, 2017 at 3:39 PM
To: F5Networks/f5-common-python <f5-common-python@noreply.github.com>
Cc: Jason Rahm <J.Rahm@F5.com>, Mention <mention@noreply.github.com>
Subject: Re: [F5Networks/f5-common-python] Feature.mgmtint (#984)


what happens if you don't have mgmt IP set?, i think it would be better if we leave create(), and just redo modify() or update() or both to use POST. This way this will be cleaner than aliasing and doing all weird voodoo stuff

@jasonrahm<https://github.com/jasonrahm>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/F5Networks/f5-common-python/pull/984#issuecomment-280469740>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AA0SS4cqM0g3-METZunqslFWvCbiOLOZks5rdMIggaJpZM4MCXct>.

2017-02-16 21:42 UTC, wojtek0806 commented
just override _update() method and make_modify() not allowed

2017-03-01 16:58 UTC, wojtek0806 requested changes
See my inline comments

2017-03-01 16:58 UTC, wojtek0806 commented on f5/bigip/tm/sys/management_ip.py
> +        self._meta_data['required_creation_parameters'].update(('name',))
that should be removed as we already have this as default in Resource super class

2017-03-01 16:58 UTC, wojtek0806 commented on f5/bigip/tm/sys/management_route.py
> +            ('name', 'network', 'gateway'))
again you can leave out the 'name' parameter as this is already there.  Should be something like this instead:

` self._meta_data['required_creation_parameters'].update(('network', 'gateway'))`

2017-03-01 16:58 UTC, wojtek0806 commented on f5/bigip/tm/sys/management_ip.py
> +    def modify(self, **kwargs):
not entirely true, there is a property called 'description', and 'app-service' which can be manipulated, so this should be allowed

2017-03-01 16:58 UTC, wojtek0806 commented on f5/bigip/tm/sys/management_ip.py
> +    def update(self, **kwargs):
not entirely true, there is a property called 'description', and 'app-service' which can be manipulated, so this should be allowed

2017-03-01 16:58 UTC, wojtek0806 commented on f5/bigip/tm/sys/test/functional/test_management_ip.py
> +def test_modify_addr(request, mgmt_root):
this needs changing due to update/modify being possible

2017-03-01 16:58 UTC, wojtek0806 commented on f5/bigip/tm/sys/test/functional/test_management_ip.py
> +def test_update_addr(request, mgmt_root):
this needs changing do to the update being possible

2017-03-01 16:59 UTC, wojtek0806 approved these changes

2017-03-01 17:01 UTC, wojtek0806 requested changes
see my inline comments and correct accordingly

2017-03-01 17:09 UTC, wojtek0806 commented on f5/bigip/tm/sys/management_ip.py
> +        return self._load(**kwargs)
nice!

2017-03-01 21:08 UTC, jasonrahm commented
ready for your re-review @wojtek0806

2017-03-01 21:36 UTC, wojtek0806 approved these changes
Looks good now, we can add 'create' test later, for Lack of 2 NAT interfaces inside VirtualBox in Vagrant is not helping. I need to talk to @caphrim007 about creating and using NAT network, this way you can have multiple interfaces with NAT on them

2017-03-01 21:37 UTC, merged